name: setup

description: Setsup all of the project dependancies

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.26.3"
        cache: true
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: "20"
    - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
      with:
       version: 10
